var browser=navigator.userAgent;$(document).ready(function(){var addToCartPopUp=$('.modalWindow');var showAddToCartPopup=$("input[type='hidden'][name='ctl00$hdnAddToCartPopup']").val()!='';if(showAddToCartPopup){if(navigator.userAgent.match(/msie /i)){var ieVersion=navigator.appVersion;if(ieVersion=="MSIE 7.0"||ieVersion=="MSIE 8.0"||ieVersion=="MSIE 8.0"){$('.modalWindow .modalWindowContainer .modalWindowProductFooter ul.listnone li').last().css({'width':'50px','padding':'0'});}}
addToCartPopUp.delay(1000).fadeIn().delay(9000).slideUp('slow');$('html,body').on('click',function(){addToCartPopUp.hide();});}
$('.emailinput').click(function(){$(this).val('').unbind('click');});$('select.jump').change(function(){window.location=$(this).val();});$('#ddlStoreLocator').change(function(){window.location=$(this).val();});function metaNavDropDown(trigger,content){function metaNavMouseIn(){metaNavDropDownTrigger.stop().removeClass('active').find(metaNavDropDownContent).hide();$(this).addClass('active').find(metaNavDropDownContent).stop().slideDown();}
function metaNavMouseOut(){$(this).find(metaNavDropDownContent).stop().slideUp();$(this).delay(5000).removeClass('active');}
var metaNavDropDownConfig={sensitivity:2,over:metaNavMouseIn,timeout:800,out:metaNavMouseOut};metaNavDropDownTrigger.hoverIntent(metaNavDropDownConfig);}
var metaNavDropDownTrigger=$('.metanav_dropdown, .socialSharing');var metaNavDropDownContent=$('ul');metaNavDropDown(metaNavDropDownTrigger,metaNavDropDownContent);var screen_height=parseInt(screen.height,10);var megaDropDown_height=parseInt($('#megaDropDown').height(),10);var screen_height_short=false;var showMiniNav=$("input[id$=showMiniNav]").val();if(!showMiniNav){showMiniNav="false";}
showMiniNav=showMiniNav.toLowerCase();if(screen_height<=768&&showMiniNav=="true"){screen_height_short=true;$('.navContainer').remove();$('div#megaDropDown').addClass('width1024');var firstItem=$('div#megaDropDown.width1024 .megaDropDownColumn .navRow:first a').text();if(firstItem=="Best Sellers"){$('div#megaDropDown.width1024 .megaDropDownColumn .navRow:first').parent().remove();}}
else{$('.navRow').each(function(){var NavRowText=$(this).text();var NavRowID=$(this).attr('id');if(!NavRowID){$(this).find('a').remove();$(this).append('<em>'+ NavRowText+'</em>');}});}
function megaDropDown(){if(navigator.userAgent.match(/msie/i)){var ieVersion=navigator.appVersion.match(/MSIE [\d.]+/);if(ieVersion=="MSIE 7.0"||ieVersion=="MSIE 8.0"||ieVersion=="MSIE 8.0"){$('ul#topnav li').first().css('padding','0');$('.navContainer .row').each(function(){$(this).find('ul').first().css('margin','0');$(this).find('ul.colBanner li').first().css('margin','0');});}}
var dropDownTrigger=$('.megaDDTrigger');var subNavTrigger=$('div#megaDropDown ul.megaDropDownColumn li span.navRow');var subNavNextTrigger;var autoComplete=$('#divSuggestions .yui-ac-content');var tooltTipContainer=$('.tooltTipContainer');var megaDropDownContainer=$('#megaDropDownContainer');var megaDropDown=$('#megaDropDown');var isHome=$('#home').length>0;var config={sensitivity:2,over:subNavMouseIn,timeout:800,out:subNavMouseOut};megaDropDownContainer.hoverIntent(config);if(isHome){megaDropDown.css({width:'195px'});megaDropDown.show();}
function subNavMouseIn(){if(!isHome&&!IsPageInMobileView()){$('.navContainer').hide();if(!dropDownTrigger.is('.active')){if(screen_height_short==false){$('.navContainer:first').show();$('.navRow:first').addClass('active');}
megaDropDown.slideDown();dropDownTrigger.addClass('active');if(autoComplete.is(':visible')){autoComplete.hide();}
if(tooltTipContainer.is(':visible')){closeToolTip();}}}}
function subNavMouseOut(){if(!isHome&&!IsPageInMobileView()){megaDropDown.removeClass('active').hide();dropDownTrigger.removeClass('active');}
else{megaDropDown.css({width:'195px'});}
$('.navContainer').hide();subNavTrigger.removeClass('active');}
$('.megaDDTrigger').click(function(){return false;});subNavTrigger.hoverIntent(function(){if(isHome){megaDropDown.css({width:'960px'});}
var navTrigger=$(this);var NavRowID=$(this).attr('id');if(NavRowID){$('.navContainer').hide();subNavTrigger.removeClass('active');$('#topContainer').show();}
else{$('.navContainer').hide();subNavTrigger.removeClass('active');if(megaDropDown.is('.active')){subNavTrigger.removeClass('active');$('.navContainer').hide();navTrigger.stop(true,true).next('.navContainer').show();navTrigger.addClass('active');}
else{$('.navContainer').hide();subNavTrigger.removeClass('active');navTrigger.addClass('active');megaDropDown.addClass('active');navTrigger.next('.navContainer').show();}}},function(){});}
megaDropDown();$(document).on('click','#productDetail .productimage .rotator a',function(){var target=$(this).attr('href');var type=$(this).attr('class');var prodVideoLightBox=$('#productDetail .productimage #ctl00_ContentPlaceHolder1_pDetailD_MediaItems1_pnlMainImage .videoContent').size();if(prodVideoLightBox==1){$('#productDetail .productimage #ctl00_ContentPlaceHolder1_pDetailD_MediaItems1_pnlMainImage .videoContent').remove();}
if(type=="prodVideo"){$('#productDetail .productimage img.mainImage').remove();$(this).next('.videoContent').clone().prependTo('#ctl00_ContentPlaceHolder1_pDetailD_MediaItems1_pnlMainImage');$('<img class="mainImage" alt="" src="/images/icons/blank.gif" />').appendTo('#productDetail .productimage #ctl00_ContentPlaceHolder1_pDetailD_MediaItems1_pnlMainImage');}
else{$('#productDetail .productimage img.mainImage').attr('src',target);}
return false;});$(".photoGallery .carousel .thumbs a").click(function(){var lrgImg=$(this).attr("href");$(".imgContainer img").attr({src:lrgImg});return false;});var isNotStoreCatalog=$('#ctl00_ContentPlaceHolder1_pDetail_pnlStoreCatalogInfo').size()==0;var embedSrc="";if(isNotStoreCatalog){embedSrc="//www.youtube.com/v/{0}?version=3&amp;hl=en_US&autoplay=1&amp;wmode=transparent&rel=0";}
else{embedSrc="//www.youtube.com/embed/{0}";}
var lastCode="";var videoContent=$('.videoContent').html();$('.videoContent').remove();$('#pnlMainVideo').append(videoContent);if($('.product_detail .rotator li').length<2){$('.product_detail .rotator').hide();}
$('.prodVideo').click(function(){var code="";if($(this).attr("id")=="lnkVideoThumb")
code=$(this).find('input[type="hidden"]').val();else
code=$(this).find('img').attr('alt');if(lastCode=="")
embedSrc=embedSrc.replace('{0}',code);else
embedSrc=embedSrc.replace(lastCode,code).replace('autoplay=0','autoplay=1');$('#pnlMainVideo iframe').attr('src',embedSrc);var e=$('#pnlMainVideo iframe');$('#pnlMainVideo').append(e);lastCode=code;return false;});$('a[href="#ctl00_ContentPlaceHolder1_pDetail_video_Container"]').click(function(){var isActive=$('a[href="#ctl00_ContentPlaceHolder1_pDetail_video_Container"]').parent().hasClass('active')
if(!isActive){var code=$('.prodVideoThumb').first().find('img').attr('alt');if(lastCode=="")
lastCode=code;if(embedSrc.lastIndexOf('{0}')>0){embedSrc=embedSrc.replace('{0}',lastCode).replace('autoplay=1','autoplay=0');}
else{embedSrc=embedSrc.replace(lastCode,code).replace('autoplay=1','autoplay=0');}
$('#pnlMainVideo embed').attr('src',embedSrc);var e=$('#pnlMainVideo embed');$('#pnlMainVideo').append(e);lastCode=code;}});function tabbedNavigation(){var isDeskTopView=!$('.mobile-only').is(':visible')||location.pathname.indexOf('contactus')>-1;if(isDeskTopView){var tabItems=[];var locationHash=location.hash;$("ul.tabs li a").each(function(){var items=$(this).attr("href");tabItems.push(items);});if(locationHash===""){if(!$('#manpage').is(':visible')){$("ul.tabs").each(function(){$("li:first",this).addClass("active").show();});}
if(!$('#brands').is(':visible')){$(".tab_content").hide();$(".tab_container").each(function(){$(".tab_content:first",this).show();});}}
else{var tabItemsIndex=jQuery.inArray(locationHash,tabItems);if(tabItemsIndex!=-1){var targetedTab=$("ul.tabs li a[href="+ locationHash+"]");var targetedTabContent=$(".tab_content"+ locationHash);if(locationHash=="#activeAll"&&$('#brands').is(':visible')){$(".tab_container div").each(function(){$(this).show();});}
else{targetedTabContent.parent().find(".tab_content").each(function(){$(this).hide();});}
targetedTab.parent().siblings().removeClass("active");targetedTab.parent().addClass("active");targetedTabContent.fadeIn();}}
$("ul.tabs li").click(function(){var activeTab=$(this).find("a").attr("href");location.hash=activeTab;return false;});}};var iframeLoading=true;$(".vert_tabcontent").hide();$(" ul.nav li:first").addClass("vert_selecttab").show();$(".vert_tabcontent:first").show();$('#store ul.nav li a').each(function(){var cont_ID=$(this).attr('href');if($(cont_ID).html().trim()){}else{$(this).parent().addClass('deactive');}});$('#content').on('click','ul.nav li',function(){if(!IsPageInMobileView()){if(!$(this).hasClass('deactive')){var activeTab=$(this).find("a").attr("href");if(activeTab=="#virtual_tour"&&iframeLoading){var iframeHtml=$("#virtual_tour").html();$("#virtual_tour").empty();$("#virtual_tour").append(iframeHtml);iframeLoading=false;}
else{$("virtual_tour").hide();}
$("ul.nav li").removeClass("vert_selecttab");$(this).addClass("vert_selecttab");$(".vert_tabcontent").hide();$(activeTab).show();}
return false;}});var hasTabs=$(".tab_content").size();if(hasTabs>=1){if($(".tabs li a").length>0){var checkTabLink=$(".tabs li a").attr("href").search(/^\//);if(checkTabLink==-1){var lastHash='';function pollHash(){if(lastHash!==location.hash){lastHash=location.hash;tabbedNavigation();}}
setInterval(pollHash,1000);tabbedNavigation();if($("#map").size>=1){map.checkResize();}}}}
if($(".productDetailTabs .tab_container .tab_content").size()==0){$(".productDetailTabs").hide();}
$('a[rel=prettyPhoto]').prettyPhoto({theme:'facebook'});var SubHeadingNav=$('.filter_selection_subheading').size();if(SubHeadingNav>=2){$('.filter_selection_subheading').eq(1).remove();}
var itemAddedToCart_ProductName=$('.prodDesc h2').text().replace(/ by .*/gim,'');var itemAddedToCart_ProductManufacturer=$('.prodDesc h2').text().replace(/^.* by /gim,'');$('.prodDesc h2 a').text(itemAddedToCart_ProductName);$('.prodManufacturer').text('By '+ itemAddedToCart_ProductManufacturer);$(window).load(function(){$('#subCatListPage .pr-snippet-review-count').each(function(){var prodRateCounter=$(this).text().replace(/ reviews/gim,'').replace(/ review/gim,'').replace(/\(no\)/gim,'');$(this).text(prodRateCounter);});});$(".toggle_container").hide();$('.sidecol ul.filter .toggle_container:first').show().parent().find('strong').addClass('active');$(".trigger").click(function(){var triggerTarget=$(this).attr("rel");if(triggerTarget){var triggerTargetShow=triggerTarget.replace(/&hide=.*/,"").replace("show=","");var triggerTargetHide=triggerTarget.replace(/.*hide=/,"");var splitTargetHide=triggerTargetHide.split(",");for(i=0;i<splitTargetHide.length;i++){$(splitTargetHide[i]).slideUp();}
var splitTargetShow=triggerTargetShow.split(",");for(j=0;j<splitTargetShow.length;j++){$(splitTargetShow[j]).show().removeClass("invis").slideDown();}
return false;}
else{$(this).toggleClass("active");$(this).next(".toggle_container").slideToggle("fast");if($('#checkout').is(':visible')){return true;}else{return false;}}});$('ul.attributes_bottom').css({'display':'none'});$('.toggle_attribute_view').click(function(){var text=$(this).text();if(text=="Hide"){$(this).removeClass('active');$(this).next('ul.attributes_bottom').slideUp();$(this).text("View More");}
else{$(this).addClass('active');$(this).next('ul.attributes_bottom').slideDown();$(this).text("Hide");}});$(".accordion .content").hide();$(".accordion h3:first").addClass("open").next().show();$(".accordion h3").click(function(){if($(this).hasClass("open")){}else{$(".accordion h3").removeClass("open");$(".accordion .content").slideUp();$(this).next().slideToggle();}
$(this).addClass("open");return false;});$.fn.switchView=function(){var thisTabContent=$(this).parents(".maincol");if($(this).val()=='thumbs'){$(thisTabContent).find('ul#ulPartTypes').removeClass('listview').addClass("gridview");$(this).parent().find('label').removeClass('listview');if($(thisTabContent).attr('id')==('videos')){$('#videos h3').each(function(){$(this).find('a').showhide();});}}else{$(thisTabContent).find('ul.gridview.col3 li:nth-child(3n+1)').removeClass("clear");$(thisTabContent).find('ul.gridview li').css("height","auto");$(thisTabContent).find('ul#ulPartTypes').removeClass('gridview').addClass("listview");$(this).parent().find('label').addClass('gridview');if($(thisTabContent).attr('id')==('videos')){$('#videos h3').each(function(){$(this).find('a').html($(this).find('a').attr('title'));});}}};$.fn.detectSwitchView=function(){if($(this).find("ul#ulPartTypes").hasClass("listview")){$(".switchview select").val('details');}else{$(".switchview select").val('thumbs');}}
$('.tab_content:first').detectSwitchView();$(".switchview select").change(function(){$(this).switchView();});$(".thumbs a:first-child").addClass("active");$(".thumbs a").click(function(){var mainImage=$(this).attr("href");$(".thumbs a").removeClass("active");$(this).addClass("active");$(".lrg_view").attr({href:mainImage+'&w=600'}).find("img").attr({src:mainImage+'&w=301'});return false;});if($('.globalbanner').size()>0){$('.globalbanner').fadeIn();$('.globalbanner').hover(function(){$(this).stop().animate({bottom:0},{duration:200,easing:'easeInOutCirc'});},function(){$(this).stop().animate({bottom:-110},{duration:200,easing:'easeInOutCirc'});});$('.globalbanner a.btn').click(function(){$(this).parent().parent().hide();saveCookieinSession('tgbanner','1');return false;});if(document.cookie.indexOf('tgbanner')>-1){$('.globalbanner a.btn').parent().parent().hide();}}
if($('#home,.contest').length==1){$('#global-banner').hide();}
else{$('#global-banner').show();}
var unitedStatesForm='.validate_US';var canadaForm='.validate_NONUS';var formExists=$(unitedStatesForm).length>0;if(formExists){var countryDropDown='.country_select select';function DetectCountry(){var selectedCountry='';$(canadaForm).hide();selectedCountry=$('.country_select option:selected').val();$(unitedStatesForm+", "+ canadaForm).hide();if(selectedCountry=='US'){$(unitedStatesForm).fadeIn();}
else if(selectedCountry=='CA'){$(canadaForm).fadeIn();}}
function DetectCountryOnDropDownChange(){$(countryDropDown).change(function(){DetectCountry();});}
DetectCountry();DetectCountryOnDropDownChange();}
$(".validate_NONUS").hide();$.fn.countryDetect=function(){var countrySelect=$('.country_select option:selected').val();$(".validate_US, .validate_NONUS").hide();if(countrySelect=='0'){}else if(countrySelect=='US'){$(".validate_US").fadeIn();}else{$(".validate_NONUS").fadeIn();}}
$(".country_select select:selected").countryDetect();$(".country_select select").change(function(){$(this).countryDetect();});$("area").click(function(){var anchorID=$(this).attr("href");var anchorIDfloat=parseFloat(anchorID.substring(1));$("ul.partlist li").removeClass("highlight");$("ul.partlist li.partnum_"+ anchorIDfloat).addClass("highlight");});var IsSafari=navigator.userAgent.indexOf("Safari")>-1&&!(navigator.userAgent.indexOf("Chrome")>0);if(IsSafari){$('#headerContainer').addClass('pc');}});$("a[rel^='prettyPhoto']").prettyPhoto();var lightbox={width:0,height:0,animation:true,screenPosition:null,ShowYMM:null,screenWidth:null,screenHeight:null,screenScrollPosition:null,TopPoss:null,LeftPoss:null,refreshInterval:500}
var IEObjectWidth;var YMMGetScreenPosition;$(document).on('click','.closeLightbox',function(){var keepOpen=$("#keepOpen").length>=1?true:false;var byPassKeepOpen=$("#byPassKeepOpen").length>=1?true:false;if(byPassKeepOpen){keepOpen=false;}
if(!keepOpen){var errorsOnPage;var buttonAction;var modalNotificationSize;var url_parameter=location.search.replace(/^\?/gim,'').replace(/=/gim,'').replace(/\d.*/gim,'');var pickInStoreDropdown=$('.dropdown_lightbox').size();if(pickInStoreDropdown>=1){var prevDropdownVal=$('.dropdown_lightbox').attr('rel');$('.dropdown_lightbox').val(prevDropdownVal);}
function hideModalNotification(){$(".growl_notification").parent().hide();}
function hide(buttonAction){errorsOnPage=$(".lightbox_container .errormsg").size();if(errorsOnPage===0||buttonAction==="cancel"){$(".filter_lightbox").find(".info").removeClass("invis");var YMMFiltersSize=$(".filter_lightbox").size();if(YMMFiltersSize===1){$("body").removeClass("filter_lightbox");$(".filterwrap").parent().addClass("dropdown_container");$(".vehicle_details").next("p").hide();}
clearInterval(YMMGetScreenPosition);if(lightbox.animation===true&&!IsPageInMobileView()){$(".vehicle_lightbox_wrapper").fadeOut().animate({opacity:0.7});$(".lightbox_container").animate({top:-99999},{duration:4000,complete:function(){$(this).hide()}});if(url_parameter=="ppe"){window.location.href="shoppingcart.aspx";}}
else{$(".vehicle_lightbox_wrapper").hide().css("opacity","0.7");$(".lightbox_container").hide();$('.lightbox_container').each(function(){$(this).css('width','auto');});if(url_parameter=="ppe"){window.location.href="shoppingcart.aspx";}}
modalNotificationSize=$(".growl_notification").size();if(modalNotificationSize>=1){setTimeout(hideModalNotification,5000);}
clearInterval(verifyFormHasBeenProcessed);}}
if($(this).attr("alt")){buttonAction=$(this).attr("alt").toLowerCase();}
else{buttonAction="cancel";}
if(buttonAction==="save"||buttonAction==="submit"){var hiddenInputValue;var verifyFormHasBeenProcessed;verifyFormHasBeenProcessed=setInterval(function(){var checkFormIndicator=['.lightbox_container input#ctl00_ContentPlaceHolder1_hf_BillingAddress_CreateEdit_IsSPD','.lightbox_container #ctl00_ContentPlaceHolder1_pDetailD_partFitment_IsSPD','.lightbox_container input#ctl00_ContentPlaceHolder1_hf_ShippingAddress_CreateEdit_IsSPD'];$.each(checkFormIndicator,function(intIndex,objValue){hiddenInputValue=parseInt($(objValue).attr("value"),10);if(hiddenInputValue===1){if($(".lightbox_container.partdetail")){errorsOnPage=$(".lightbox_container.partdetail .errormsg").size();if(errorsOnPage===0){clearInterval(verifyFormHasBeenProcessed);$(".lightbox_container #ctl00_ContentPlaceHolder1_pDetailD_partFitment_IsSPD").attr("value","0");hide(buttonAction);}}
else{clearInterval(verifyFormHasBeenProcessed);hide(buttonAction);}}});},100);}
else{hide(buttonAction);}
var exclusions=['ctl00_ContentPlaceHolder1_ibtn_BillingAddress_CreateEdit_Save','ctl00_ContentPlaceHolder1_ibtn_ShippingAddress_CreateEdit_Save','ctl00_ContentPlaceHolder1_pDetailD_partFitment_ibtnGo','ctl00_ContentPlaceHolder1_btnCalculate'];var elementID=$(this).attr('id');if(jQuery.inArray(elementID,exclusions)==-1){return false;}}});function lightboxSlideOnScreen(getLightboxTarget,getLightboxTargetOptions){var vs_image_list=$('.vs_image_list').text().replace(/[ \t\r\n]/gim,"");if(vs_image_list==""){$('.vs_image_list, .or').remove();$('.filter_lightbox .lightbox_container#ymm_filter').css('width','auto');}
function lightBoxGetPosition(getLightboxTarget){lightbox.screenWidth=$(window).width();lightbox.screenHeight=$(window).height();lightbox.screenScrollPosition=jQuery(window).scrollTop();lightbox.Width=$("#"+ getLightboxTarget+".lightbox_container").width();lightbox.Height=$("#"+ getLightboxTarget+".lightbox_container").height();lightbox.TopPoss=(((lightbox.screenHeight- 200)- lightbox.Height)/ 2) + lightbox.screenScrollPosition;lightbox.LeftPoss=(lightbox.screenWidth- lightbox.Width)/ 2;return lightbox.screenWidth,lightbox.screenHeight,lightbox.screenScrollPosition,lightbox.Width,lightbox.Height,lightbox.TopPoss,lightbox.LeftPoss;}
lightBoxGetPosition(getLightboxTarget);$(".lightbox_container").each(function(){var elementID=$(this).attr('id');var exclusions=['ymm_filter'];if(jQuery.inArray(elementID,exclusions)==-1){$("#"+ elementID+".lightbox_container").hide();}});$("#"+ getLightboxTarget+".lightbox_container").css({"left":lightbox.LeftPoss});$("#"+ getLightboxTarget+".lightbox_container").css({"top":lightbox.screenScrollPosition- lightbox.Height});$("#"+ getLightboxTarget+".lightbox_container:first").show();if(getLightboxTargetOptions=="hideVehicleGroup"){var leftPos=(lightbox.screenWidth- 450)/ 2;$("#"+ getLightboxTarget+".lightbox_container:first").css('left',leftPos);}
if(lightbox.animation===true){$("#"+ getLightboxTarget+".lightbox_container:first").stop().animate({"top":lightbox.TopPoss});}
else{if(IEObjectWidth==null){IEObjectWidth=$("#"+ getLightboxTarget+".lightbox_container").width();}
$("#"+ getLightboxTarget+".lightbox_container:first").stop().css("top",lightbox.TopPoss).show().css('width',IEObjectWidth);}
if(!IsPageInMobileView()){YMMGetScreenPosition=setInterval(function(){lightBoxGetPosition(getLightboxTarget);if(lightbox.animation===true){$(".vehicle_lightbox_wrapper").css({"width":lightbox.screenWidth,"height":lightbox.screenHeight});$("#"+ getLightboxTarget+".lightbox_container:first").stop().animate({"top":lightbox.TopPoss,"left":lightbox.LeftPoss});}},lightbox.refreshInterval);}};$(document).on("click",".openLightbox",function(){clearInterval(YMMGetScreenPosition);getLightboxTarget=$(this).attr("rel").replace(/\[.*\]/gim,'');getLightboxTargetOptions=$(this).attr("rel").replace(/\w.*\[/gim,'').replace(/\[/gim,'').replace(/\]/gim,'');if(getLightboxTargetOptions!='nobg'){$(".vehicle_lightbox_wrapper").hide().css("opacity","0.7").fadeIn();}
var elementID=$(this).attr('id');var exclusions=['ymm_filter'];if(jQuery.inArray(elementID,exclusions)==-1){$("#"+elementID+".lightbox_container").hide();}
lightboxSlideOnScreen(getLightboxTarget,getLightboxTargetOptions);if(getLightboxTargetOptions!=='defaultNetAction'){return false;}});$(window).load(function(){var userAgent=navigator.userAgent;if((userAgent.match(/iPhone/i))||(userAgent.match(/iPad/i))||(userAgent.match(/maemo/i))||(userAgent.match(/android/i))||(userAgent.match(/webos/i))||(userAgent.match(/MSIE 6/i))||(userAgent.match(/MSIE 7/i))||(userAgent.match(/MSIE 8/i))){lightbox.animation=false;$('.lightbox_container').each(function(){lightbox.width=parseInt($(this).width(),10)+ 20;$(this).css("width",lightbox.width);});}});function carousel(thisCarousel){var rotatorLi=thisCarousel.find('ul.rotator li').width();var rotatorSum=thisCarousel.find('ul.rotator li').size();var carousel=thisCarousel.width();var scrollTriggerHeight=parseInt(thisCarousel.parent().find('a.right-scroll').height(),10);var itemIMGHeight=$('#ymm_filter').size()>=1?parseInt($('#ymm_filter .carousel ul.rotator li:first').height(),10)+ 65:parseInt(thisCarousel.find('ul.rotator li img:first').height(),10);var rotatorMaxLi=Math.floor(carousel/rotatorLi);var rotatorSlideSum=Math.ceil(rotatorSum/rotatorMaxLi);var adjustLi=(carousel/rotatorMaxLi);var adjustRotator=(adjustLi*rotatorSum);var lastSlideSum=Math.floor(adjustRotator/carousel);var lastSlide=(carousel*lastSlideSum)- adjustRotator;thisCarousel.find('ul.rotator li').delay(500).animate({'width':adjustLi,easing:'jswing'},200);thisCarousel.find('ul.rotator').delay(500).animate({'width':adjustRotator,easing:'jswing'},200);var sum=0;if(carousel<adjustRotator){if(itemIMGHeight!=0){var scrollerPosition=((itemIMGHeight-(scrollTriggerHeight/2))/ 2);thisCarousel.parent().find('a.right-scroll, a.left-scroll').css('top',scrollerPosition);}
thisCarousel.parent().delay(1500).find('a.right-scroll, a.left-scroll').fadeIn('slow');thisCarousel.parent().find('a.right-scroll').click(function(){if(sum<(rotatorSlideSum- 1)){sum++;thisCarousel.parent().find('a.left-scroll').removeClass('deactive');switch(sum){case rotatorSlideSum:thisCarousel.parent().addClass('deactive');break;case rotatorSlideSum- 1:thisCarousel.parent().find('a.right-scroll').addClass('deactive');if(lastSlide<-1){thisCarousel.parent().find('ul.rotator').animate({marginLeft:'+='+ lastSlide},{duration:"slow",easing:"easeInOutExpo"});}
else{thisCarousel.parent().find('ul.rotator').animate({marginLeft:'-='+ carousel},{duration:"slow",easing:"easeInOutExpo"});}
break;default:thisCarousel.parent().find('ul.rotator').animate({marginLeft:'-='+ carousel},{duration:"slow",easing:"easeInOutExpo"});break;}}
return false;});thisCarousel.parent().find('a.left-scroll').addClass('deactive');thisCarousel.parent().find('a.left-scroll').click(function(){if(sum>0){sum--;thisCarousel.parent().find('a.right-scroll').removeClass('deactive');switch(sum){case 0:if(lastSlide<-1&&rotatorSlideSum==2){thisCarousel.parent().find('ul.rotator').animate({marginLeft:'-='+ lastSlide},{duration:"slow",easing:"easeInOutExpo"});}
else{thisCarousel.parent().find('ul.rotator').animate({marginLeft:'+='+ carousel},{duration:"slow",easing:"easeInOutExpo"});}
thisCarousel.parent().find('a.left-scroll').addClass('deactive');break;case rotatorSlideSum- 2:if(lastSlide<-1){thisCarousel.parent().find('ul.rotator').animate({marginLeft:'-='+ lastSlide},{duration:"slow",easing:"easeInOutExpo"});}
else{thisCarousel.parent().find('ul.rotator').animate({marginLeft:'+='+ carousel},{duration:"slow",easing:"easeInOutExpo"});}
break;default:thisCarousel.parent().find('ul.rotator').animate({marginLeft:'+='+ carousel},{duration:"slow",easing:"easeInOutExpo"});break;}}
return false;});}else{thisCarousel.find('a.right-scroll, a.left-scroll').hide();}};function initCarousel(){$('div.carousel').each(function(){var produtDetailCarousel=$(this).parent().parent().parent().attr('class');var productDetailCarouselSize=$(this).find('.rotator li').size();var thisCarousel=$(this);if(produtDetailCarousel=="prod_view"&&productDetailCarouselSize==1){}
else{if(produtDetailCarousel=="prod_view"){$(this).parents('.carousel_wrap').show();}
carousel(thisCarousel);}});}
$(window).load(function(){$('#ymm_filter').size()>=1?'':initCarousel();$('.products ul.filter li strong').click(function(){var liClass=$(this).attr('class');if(liClass=="active"){$(this).removeClass('active');$(this).parents('.searchfilter ul').find('li').not(':first').slideDown();$(this).parents('ul.attributes_top').next('.toggle_attribute_view').show();if($(this).parents('ul.attributes_top').next('.toggle_attribute_view').hasClass('active')){$(this).parents('ul.attributes_top').next('.toggle_attribute_view').next('ul.attributes_bottom').show();}}
else{$(this).addClass('active');$(this).parents('.searchfilter ul').find('li').not(':first').slideUp();$(this).parents('ul.attributes_top').next('.toggle_attribute_view').hide();$(this).parents('ul.attributes_top').next('.toggle_attribute_view').next('ul.attributes_bottom').hide();}});$("#catidselector select").change(function(){$("ul.col1 li, .js_message").fadeOut('fast');var catidVal=$(this).val();if($("li").hasClass("catid_"+ catidVal)){$("li.catid_"+ catidVal).fadeIn('fast');}else if(catidVal=='-1'){$("ul.col1 li").show();}});});$(document).ready(function(){var browser=navigator.userAgent;var bannerExists=$('.homebannerblocktrigger').length;function runBannerSlideShow(){if($('.homebannerblocktrigger ul li.active').nextAll().size()!==0){activeBanner.imgSrc=$('.homebannerblocktrigger ul li.active').next().find('a').attr('href');activeBanner.linkTo=$('.homebannerblocktrigger ul li.active').next().find('a').attr('rel');activeBanner.alt=$('.homebannerblocktrigger ul li.active').next().find('a').find('span').text();activeBanner.trigger=$('.homebannerblocktrigger ul li.active').next();}
else{activeBanner.imgSrc=$('.homebannerblocktrigger ul li:first a').attr('href');activeBanner.linkTo=$('.homebannerblocktrigger ul li:first a').attr('rel');activeBanner.alt=$('.homebannerblocktrigger ul li:first a span').text();activeBanner.trigger=$('.homebannerblocktrigger ul li:first');}
$('.homebannerblock a').attr('href',activeBanner.linkTo).find('img').attr({src:activeBanner.imgSrc,alt:activeBanner.alt});$('.homebannerblocktrigger ul li').removeClass('active');activeBanner.trigger.addClass('active');}
if(bannerExists==1){var activeBanner={'imgSrc':$('.homebannerblock img').attr('src'),'linkTo':$('.homebannerblock a').attr('href'),'alt':$('.homebannerblock img').attr('alt'),'trigger':''};$(".homebannerblocktrigger ul").prepend('<li><a href="'+ activeBanner.imgSrc+'" rel="'+ activeBanner.linkTo+'"><span>'+ activeBanner.alt+'</span></a></li>');var bannerSlideShow={active:false,'size':$(".homebannerblocktrigger li").size(),'duration':7000,width:function(){var eachWidth=0;$('.homebannerblocktrigger li').each(function(){eachWidth+=parseInt($(this).width(),10)+ 30;});return eachWidth;}}
if(bannerSlideShow.size>=2){$('.homebannerblocktrigger ul').css({width:bannerSlideShow.width()}).find('li').fadeIn();$('.homebannerblocktrigger ul li:first').addClass('active');playBannerSlideshow=setInterval(runBannerSlideShow,bannerSlideShow.duration);}
$('#content').on('click','.homebannerblocktrigger ul li a',function(e){e.preventDefault();activeBanner.imgSrc=$(this).attr('href');activeBanner.linkTo=$(this).attr('rel');activeBanner.alt=$(this).find('span').text();$('.homebannerblock a').attr('href',activeBanner.linkTo).find('img').attr({src:activeBanner.imgSrc,alt:activeBanner.alt});$('.homebannerblocktrigger ul li').removeClass('active');$(this).parent().addClass('active');clearInterval(playBannerSlideshow);});}
if((browser.match(/MSIE 6/i))||(browser.match(/MSIE 7/i))||(browser.match(/MSIE 8/i))){//#col4 adjustment on 4th list item
$('ul.col4 li:nth-child(4n+4), ul.col3 li:nth-child(3n+3)').css({'margin-right':'0'});$('#content .products ul.col4 li:nth-child(4n+1),#subCatListPage .colProducts li:nth-child(3n+1),ul.col3 li:nth-child(3n+1),ul.col4 li:nth-child(4n+1),ul.col5 li:nth-child(5n+1)').css({'clear':'both'});$('#content .products ul.col4 li:nth-child(3n+1)').css({'clear':'none'});$('#productDetail .communitySharing ul li').eq(0).css('width','258px');var productDetailHeight=parseInt($('#productDetail').height(),10)*2;$('#productDetail').css({'height':productDetailHeight});}});$(function(){var promoThreshold=10;var detailsThreshold=8;var promoCount=$('.promotext > div').size();if(promoCount>promoThreshold){ShowHidePromos();}
var detailsCount=$('.productDetails .specs li').size();if(detailsCount>detailsThreshold){ShowHideDetails();}
$('#promoShowHide').click(function(){isHidden=$('#hdnPromos').is(':hidden');if(isHidden){$('#promoShowHide').text('Less');$('#hdnPromos').show();}
else{$('#promoShowHide').text('More')
$('#hdnPromos').hide();}});$('#detailsShowHide').click(function(){isHidden=$('#hdnDetails').is(':hidden');if(isHidden){$('#detailsShowHide').text('Less Details');$('#hdnDetails').show();}
else{$('#detailsShowHide').text('More Details')
$('#hdnDetails').hide();}});var isNotStoreCatalog=$('#ctl00_ContentPlaceHolder1_pDetail_pnlStoreCatalogInfo').size()==0;var isDetailPage=$('#productDetail .right-col').size()>0;if(isNotStoreCatalog&&isDetailPage){var floatBox='#productDetail .right-col';var floatBoxStart=$(floatBox).offset().top- parseFloat($(floatBox).css('marginTop').replace(/auto/,0));$(window).scroll(function(){var viewPortPosition=$(window).scrollTop();var headerHeight=$('#headerContainer').height()+ $('#metanav').height();var bodyHeight=$('.container').height();var floatBoxHeight=$(floatBox).height();var stopPosition=bodyHeight- floatBoxHeight;if(viewPortPosition>=stopPosition&&stopPosition>headerHeight){$(floatBox).removeClass('fixed');$(floatBox).css({position:'absolute',top:stopPosition});}
else{$(floatBox).css({position:'',top:''});var floatBoxPosition=headerHeight+ floatBoxStart+ floatBoxHeight;var maxFloatBoxScrollPosition=headerHeight+ bodyHeight- 20;var bottomNotReached=floatBoxPosition<maxFloatBoxScrollPosition;if(viewPortPosition>=floatBoxStart&&bottomNotReached){$(floatBox).addClass('fixed');}
else{$(floatBox).removeClass('fixed');}}});}});var promoLink="<a id='promoShowHide' href='javascript:void(0);'>Show More</a>";var ShowHidePromos=function(){$('.promotext > div').each(function(index,value){if(index>1){if($(value).attr('id')!='hdnPromos'){$('#hdnPromos').append(value);}}});$('.productDetails .promotext').append(promoLink);};var detailsLink="<a id='detailsShowHide' href='javascript:void(0);'>More Details</a>";var ShowHideDetails=function(){$('.productDetails .specs > li').each(function(index,value){if(index>7){if($(value).attr('id')!='hdnDetails'){$('#hdnDetails').append(value);}}});$('#hdnDetails').parent().append(detailsLink);};